spring:
  application:
    name: springbootstarwars
  jmx:
    enabled: true
  #dev, pre, pro
  profiles:
    active: pro
  security:
    user:
      name: admin
      password: 12345
      roles: [ADMIN]

server:
  port: 8762

management:
  endpoints:
    web:
      exposure:
        include: "*"

url:
  #connection_timeout: 30000
  #maxBytesInMemory: 30000000
  ds_test: https://swapi.py4e.com/api/vehicles/
  secret: SgVkYp3s6v9y$B&E)H+MbQeThWmZq4t7
  headerString: Authorization
  authoritiesClaim: authorities
  err: Auth Error, Token Unavailable

logging:
  level:
    root: INFO
    "[org.springframework]": ERROR
    "[com.businessassistantbcn]": INFO
  pattern:
    # console: Spring's default
    file: "%date %5level %-40.40logger{39} [%thread] %msg%n"
#  file:
#    name: opendata.log
