spring:
  application:
    name: spring-boot-zmq
    version: 1.0.0-SNAPSHOT
  jmx:
    enabled: true

springdoc:
  swagger-ui:
    path: "/swagger-ui-custom.html"
    operationsSorted: method
  api-docs:
    enable: true
    path: "/api-docs"

server:
  port: 8762

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false

zeromq:
  socket:
    address: tcp://*:5555

logging:
  level:
    root: INFO
    "[org.springframework]": ERROR
    "[com.itachallenge]": INFO
  pattern:
    # console: Spring's default
    file: "%date %5level %-40.40logger{39} [%thread] %msg%n"
#  file:
#    name: itachallenge-challenge.log

url:
  connection_timeout: 30000
  maxBytesInMemory: 30000000

messages:
  errorMessage: "Invalid values."

